version: '3.4'

services:
  babelhelpersimpleaccess:
    image: babelhelpersimpleaccess
    build:
      context: simpleCity-app-frontend/node_modules/@babel/helper-simple-access
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "./lib/index.js"]
